#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1

start_service() {
	config_load blockadeip
	local enabled
	config_get_bool enabled main enabled 1
	[ "$enabled" = "1" ] || return 0

	/usr/sbin/blockadeip init >/dev/null 2>&1

	procd_open_instance
	procd_set_param command /usr/sbin/blockadeip daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	/usr/sbin/blockadeip stop >/dev/null 2>&1
}

reload_service() {
	/usr/sbin/blockadeip reload >/dev/null 2>&1
}
